export default {
    products: [
        {
            id: '1',
            title: "HOLISTIC HAIR",
            subTitle: "Sensitive Conditioner",
            image: "./app/assets/product1.png",
            bonusBadge: true,
            newBadge: true,
            saleBadge: true,
            mindfullBadge: true,
            mindfullImage: "app/assets/mindful-brand.svg",
            cardOptions: "500ml|250ml",
            dropdown: true,
            cardOptionD: "250ml",
            cardAmountD: "NZ$23.90",
            discountAmount: "NZ$23.90",
            oldAmount: "RRP NS$31.99",
            rating: 4,
            reviews: 24
        },
        {
            id: '2',
            title: "HOLISTIC HAIR",
            subTitle: "Sensitive Conditioner",
            image: "./app/assets/product1.png",
            bonusBadge: false,
            newBadge: true,
            saleBadge: true,
            mindfullBadge: true,
            mindfullImage: "app/assets/mindful-brand.svg",
            cardOptions: "500ml|250ml",
            dropdown: true,
            cardOptionD: "250ml",
            cardAmountD: "NZ$22.90",
            discountAmount: "NZ$22.90",
            oldAmount: "RRP NS$31.99",
            rating: 4,
            reviews: 24
        },
        {
            id: '3',
            title: "AOTEAROAD",
            subTitle: "Natural Hold Hair Clay",
            image: "./app/assets/product2.png",
            bonusBadge: false,
            newBadge: false,
            saleBadge: true,
            mindfullBadge: false,
            mindfullImage: "app/assets/mindful-brand.svg",
            cardOptions: "65gm",
            dropdown: false,
            cardOptionD: "",
            cardAmountD: "",
            discountAmount: "NZ$12.90",
            oldAmount: "",
            rating: 4,
            reviews: 24
        }
    ]
}